yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
百度（BAIDU.COM）：公网域名和内网域名混用
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
阿里巴巴（ALIBABA.COM）：INC和.NET是最喜欢用作内网域名
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
腾讯(TENCENT.COM)：用了一个不是自己的域名
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
京东（JD.COM）：特征独一无二，比较准
jd.local
360（360.CN）：特征独一无二，比较准
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
饿了么(ELE.ME)：特征独一无二，比较准
elenet.me
陌陌（IMMOMO.COM）：特征独一无二，比较准
wemomo.com
搜狐（sohu.com）：喜欢INC
sohu-inc.com
sohuno.com
cyou-inc.com
途牛（TUNIU.COM）：喜欢ORG
tuniu.org
tuniu-cie.org
tunie-sit.org
去哪儿（QUNAR.COM）：和百度类似，但用二级域来区分，比百度清楚
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
携程（CTRIP.COM）：：特征独一无二，比较准
ctripqa.com
ctripcorp.com
爱奇艺（IQIYI.COM）：爱奇艺是区分的最好的，数据库、应用间调用、人访问的都区分开了
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
yx01.baidu.com
vm.baidu.com
epc.baidu.com
iwm.name
xdb.all.serv
alibaba-inc.com
aliyun-inc.com
alibaba-inc.vipserver
alibaba.net
alipay.net
fliggy.net
taobao.net
tapd.oa.com
proxy.tencent.com
proxy.oa.com
npm.oa.com
tencentdb.com
tencent.com
jd.local
qihoo.net
Bilibili（BILIBILI.COM）：CO域名和COM域名在搜索分词容易出问题，需要注意
bilibili.co
elenet.me
wemomo.com
sohu-inc.com
sohuno.com
cyou-inc.com
tuniu.org
tuniu-cie.org
tunie-sit.org
dev.qunar.com
package.qunar.com
test.qunar.com
beta.qunar.com
local.qunar.com
corp.qunar.com
ctripqa.com
ctripcorp.com
qiyi.domain
qiyi.virtual
qiyi.db
